export default [
  {
    files: ["**/*.js"],
    ignores: ["node_modules/**", "dist/**", "eslint.config.js", "vitest.config.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        document: "readonly",
        window: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        alert: "readonly",
        fetch: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        URL: "readonly",
        Date: "readonly",
        Math: "readonly",
        JSON: "readonly",
        HTMLElement: "readonly",
        Event: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        QRCode: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "warn",
      "no-var": "error",
      "prefer-const": "warn",
      "eqeqeq": ["warn", "always"],
      "no-console": "off",
    },
  },
];
